### ISSUE TITLE
can this works with next.js ?

### ISSUE THREAD

**Issue by dfang** [pbeshai/use-query-params#13]
hi, can this lib works with next.js ?

i got this error on page ....

```
TypeError: Cannot read property 'search' of undefined
```

**Comment by pbeshai** [comment]
Hmm, I suppose this is due to `window.location` not being a thing. I've never used next.js though, would you be able to reproduce this in an example repo I could use to debug?

**Comment by zielinsm** [comment]
I've ran into similar issue with Gatsby:
`error Building static HTML failed for path "/"
(...)
WebpackError: TypeError: Cannot read property 'search' 
  of undefined`
I suppose that [this](https://github.com/reach/router/issues/222) for @reach/router could point us in the right direction with preventing this from happening.

**Comment by nickhavenly** [comment]
Just wanted to add a +1 to this issue. It would be nice to use this with SSR applications and @zielinsm seems to have a working fix ready.

**Comment by gcloeval** [comment]
Would also love to usue this SSR (nextjs in particular), have you made any progress @nickhavenly  ?

**Comment by zielinsm** [comment]
@nickhavenly, I have made some changes to the PR I submitted after finding out I wasn't returning a value adjusted to the environment. This should be working now.
I've re-requested a review from @pbeshai.

**Comment by gcloeval** [comment]
From what I understand so far, it seems to me that this would allow it to just perhaps pass/build successfully. I am wondering if @nickhavenly  actually wanted to look into building something like currently supported ReactRouter / ReachRouter providers, i.e. NextRouterProvider?

For example, if I click on a "filter" component and update a value, I would be getting a new request on the next SSR server with new value of the filter, so I can fetch different data on the servers getInitilProps? I am also first time working with nextjs so I am not 100% sure how involved that is.

**Comment by nickhavenly** [comment]
@gcloeval @zielinsm,

I was able to get it working in a similar fashion to PR #25 but after getting to that point realized that I needed to integrate with NextRouter for my use case. My deadline was too tight to spend time on this so I ended up rolling my own rudimentary solution which interfaced directly with next router.

For non-package specific SSR @zielinsm's PR should be sufficient but I think the correct long term solution here is to integrate a NextRouterProvider as @gcloeval suggested. Unfortunately I'm still pushing against tight deadlines and don't have the extra bandwidth to pursue this as an option at the moment. Hopefully someone else can carry the torch as this is a really neat package and I'd love to refactor for it in the future.

**Comment by gcloeval** [comment]
@nickhavenly  - yeah same here, bulding a proper NextRouterProvider seems a bit too over my head at the moment. 
Do you mind sharing your rudimentary soltion, or at least some snippets what you ended up using - maybe a) I can also use it for my app and b) it can be a good starting point if somebody wants to pick it up here?

**Comment by lucasconstantino** [comment]
```tsx
/**
 * Next.js query param provider.
 */
const QueryProvider: React.FC = ({ children }) => {
  const router = useRouter()

  // eslint-disable-next-line no-shadow
  const history = {
    push: ({ search }: Location) =>
      router.push({ search, pathname: router.pathname }),

    replace: ({ search }: Location) =>
      router.replace({ search, pathname: router.pathname }),
  }

  // eslint-disable-next-line no-shadow
  const location = {
    search: router.asPath.replace(/[^?]+/u, ''),
  } as Location

  return (
    <QueryParamProvider history={history} location={location}>
      {children}
    </QueryParamProvider>
  )
}
```

**Comment by Romcol** [comment]
If you are using Reach Router like me this might help : https://github.com/pbeshai/use-query-params/issues/51#issuecomment-546393827 ;)

**Comment by Romcol** [comment]
If you use Reach router, see https://github.com/pbeshai/use-query-params/issues/51#issuecomment-546393827. It could help :)

**Comment by mikestopcontinues** [comment]
Just wanted to add some small updates (useMemo, really) onto @lucasconstantino's work. (Thanks for doing the brunt of the job!)

```js
// import

import React, {memo, useMemo} from 'react';
import pt from 'prop-types';
import {useRouter} from 'next/router';
import {QueryParamProvider as ContextProvider} from 'use-query-params';

// component

export function QueryParamProvider(props) {
  const {children, ...rest} = props;
  const router = useRouter();

  const location = useMemo(() => (process.browser ? window.location : {
    search: router.asPath.replace(/[^?]+/u, ''),
  }), [router.asPath]);

  const history = useMemo(() => ({
    push: ({search}) => router.push({search, pathname: router.pathname}),
    replace: ({search}) => router.replace({search, pathname: router.pathname}),
  }), [router.pathname]);

  return (
    <ContextProvider {...rest} history={history} location={location}>
      {children}
    </ContextProvider>
  );
}

QueryParamProvider.propTypes = {
  children: pt.node,
};

// export

export default memo(QueryParamProvider);

```

**Comment by stevewillard** [comment]
Has anyone gotten the above provider to work with Next? I'm getting a `Cannot read 'split' of  undefined` when trying to use `useQueryParam`.

**Comment by fccoelho7** [comment]
Having the same issue above.

> Cannot read 'split' of undefined

**Comment by yuri-scarbaci-lenio** [comment]
Currently implemented this (a typescript adapted version of @mikestopcontinues ) in my next.js and it's working like a charm.

Only thing I'm not really a fan of is how we are supposed to handle the "initial state" by having to set it manually in `componentDidMount` but that's not a problem with the next.js/ssr it's part of the library logic itself.

the above `split of undefined` problem are most probably due to the fact that the pages reads the query on load and if no query is found your state is indeed undefined, and you can go around that with something like this:
```
   // create your defaultState variable
    const defaultQuery = {
        filters: {
            tags: [],
            category: undefined,
            textSearch: undefined,
        }
    }
 // on mount smart merge the existing query with your default values
    useEffect(
        () => {
            setQuery({
                ...defaultQuery,
                ...(query.filters && { filters: { ...query.filters } }) // if a value is present in the first load query url, it overwrite the default values
            }, 'replace'); // we want to replace because we don't want unexpected states, if you need something else feel free to change this
        },
        []
    )
```

**Comment by baybara-pavel** [comment]
If you use https://nextjs.org/docs/routing/dynamic-routes you should modify @mikestopcontinues example
```js
import React, { memo, useMemo } from 'react';
import { useRouter } from 'next/router';
import { QueryParamProvider as ContextProvider, QueryParamContextValue } from 'use-query-params';

export const QueryParamProviderComponent = (props: { children?: React.ReactNode }) => {
  const { children, ...rest } = props;
  const router = useRouter();
  const match = router.asPath.match(/[^?]+/);
  const pathname = pathNameMatch ? match[0] : router.asPath;

  const location = useMemo(
    () =>
      process.browser
        ? window.location
        : ({
            search: router.asPath.replace(/[^?]+/u, ''),
          } as QueryParamContextValue['location']),
    [router.asPath],
  );

  const history = useMemo(
    () => ({
      push: ({ search }: QueryParamContextValue['location']) =>
        router.push(router.pathname, { search, pathname }, { shallow: true }),
      replace: ({ search }: QueryParamContextValue['location']) =>
        router.replace(router.pathname, { search, pathname }, { shallow: true }),
    }),
    [pathname, router],
  );

  return (
    <ContextProvider {...rest} history={history} location={location}>
      {children}
    </ContextProvider>
  );
};

export const QueryParamProvider = memo(QueryParamProviderComponent);
```

**Comment by brycereynolds** [comment]
@baybara-pavel what should `pathNameMatch` be in your example?

**Comment by brycereynolds** [comment]
Actually, it looks like maybe just a check on `match`?

**Comment by baybara-pavel** [comment]
@brycereynolds, yep you right, thank you, just my typo. Fixed my original comment.

**Comment by matt-dutchie** [comment]
@baybara-pavel thanks for this example. We ended up changing the `push`/`replace` functions to:

```js
router.push(`${router.pathname}${search}`, { search, pathname }, { shallow: true });
// and
router.replace(`${router.pathname}${search}`, { search, pathname }, { shallow: true });
```

In order to avoid this bug in next.js's router when doing client-side navigation:

https://github.com/zeit/next.js/issues/9473

**Comment by STEVEOO6** [comment]
@matt-dutchie I used a different approach to solve the same issue.

```
router.push({ pathname: router.pathname, query: router.query }, { search, pathname }, { shallow: true });
// and
router.replace({ pathname: router.pathname, query: router.query }, { search, pathname }, { shallow: true });
```

**Comment by Regaddi** [comment]
@baybara-pavel Thanks for your example! This is great!

I had to change it slightly, since `QueryParamContextValue` doesn't seem to be exported anymore:

```ts
import React, { memo, useMemo } from 'react';
import { useRouter } from 'next/router';
import { QueryParamProvider as ContextProvider } from 'use-query-params';

export const QueryParamProviderComponent = (props: {
  children?: React.ReactNode;
}) => {
  const { children, ...rest } = props;
  const router = useRouter();
  const match = router.asPath.match(/[^?]+/);
  const pathname = match ? match[0] : router.asPath;

  const location = useMemo(
    () =>
      process.browser
        ? window.location
        : ({
            search: router.asPath.replace(/[^?]+/u, ''),
          } as Location),
    [router.asPath]
  );

  const history = useMemo(
    () => ({
      push: ({ search }: Location) =>
        router.push(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
      replace: ({ search }: Location) =>
        router.replace(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
    }),
    [pathname, router]
  );

  return (
    <ContextProvider {...rest} history={history} location={location}>
      {children}
    </ContextProvider>
  );
};

export const QueryParamProvider = memo(QueryParamProviderComponent);
```

Also included the changes as proposed by @STEVEOO6, thanks for that, too!

**Comment by tbntdima** [comment]
@Regaddi thanks for your solution, it worked for me ❤️ 

Just a few things my typescript was complaining about:

- should use `u` flag. I'm not good at regexp, so not sure if it's necessary.
```js

  const match = router.asPath.match(/[^?]+/);
```
- `push` and `replace` return promises and should use `async` & `await`

```js
    () => ({
      push: ({ search }: Location) =>
        router.push(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
      replace: ({ search }: Location) =>
        router.replace(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
    }),
    [pathname, router]
  );
```

**Comment by essential-randomness** [comment]
Was having one small problem with @Regaddi 's solution (which, this aside, works perfectly): **history** itself needs to also export location, so:

```javascript
 const history = useMemo(
    () => ({
      push: ({ search }: Location) =>
        router.push(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
      replace: ({ search }: Location) => {
        router.replace(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        );
      },
      location,
    }),
    [pathname, router.pathname, router.query, location]
  );
```

without this,  [LocationProvider.js](https://github.com/pbeshai/use-query-params/blob/master/src/LocationProvider.tsx#L75) would be using its most recently stored locationRef rather than the present location in the browser, which causes it to use an outdated location if you're updating the query params as you're moving away from a page (basically in the hooks version of "componentWillUnmount").

**Comment by chrisneven** [comment]
If you only use `use-query-params` that's fine as its params returned from the hook will update accordingly when using the setter. However, I noticed that when using this solution along with `useRouter`,  the router query object contained some stale params. To solve this we need to pass the `router.query` to the `as` (2nd parameter) argument as well. 

So basically like this:

```typescript
router.replace(
    { pathname: router.pathname, query: router.query },
    { search, pathname, query: router.query },
    { shallow: true, scroll: false }
);
```

**Comment by yantakus** [comment]
Here's a complete example code based on all the previous answers:

```
import React, { memo, useMemo } from 'react'
import { useRouter } from 'next/router'
import { QueryParamProvider as ContextProvider } from 'use-query-params'

export const QueryParamProviderComponent = (props: {
  children?: React.ReactNode
}) => {
  const { children, ...rest } = props
  const router = useRouter()
  const match = router.asPath.match(/[^?]+/)
  const pathname = match ? match[0] : router.asPath

  const location = useMemo(
    () =>
      typeof window !== 'undefined'
        ? window.location
        : ({
            search: router.asPath.replace(/[^?]+/u, ''),
          } as Location),
    [router.asPath]
  )

  const history = useMemo(
    () => ({
      push: ({ search }: Location) =>
        router.push(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
      replace: ({ search }: Location) => {
        router.replace(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        )
      },
      location,
    }),
    [pathname, router.pathname, router.query, location.pathname]
  )

  return (
    <ContextProvider {...rest} history={history} location={location}>
      {children}
    </ContextProvider>
  )
}

export const QueryParamProvider = memo(QueryParamProviderComponent)
```

Also replaced `process.browser` check with `typeof window !== 'undefined'` which is the right way of doing this (officially recommended).

**Comment by baybara-pavel** [comment]
``
```typescript
import React, { memo, useMemo } from 'react'
import { useRouter } from 'next/router'
import { QueryParamProvider as ContextProvider } from 'use-query-params'

export const QueryParamProviderComponent = (props: {
  children?: React.ReactNode
}) => {
  const { children, ...rest } = props
  const router = useRouter()
  const match = router.asPath.match(/[^?]+/)
  const pathname = match ? match[0] : router.asPath

  const location = useMemo(
    () =>
      typeof window !== 'undefined'
        ? window.location
        : ({
            search: router.asPath.replace(/[^?]+/u, ''),
          } as Location),
    [router.asPath]
  )

  const history = useMemo(
    () => ({
      push: ({ search }: Location) =>
        router.push(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        ),
      replace: ({ search }: Location) => {
        router.replace(
          { pathname: router.pathname, query: router.query },
          { search, pathname },
          { shallow: true }
        )
      },
      location,
    }),
    [pathname, router.pathname, router.query, location.pathname]
  )

  return (
    <ContextProvider {...rest} history={history} location={location}>
      {children}
    </ContextProvider>
  )
}

export const QueryParamProvider = memo(QueryParamProviderComponent)
```

**Comment by fpolic-profico** [comment]
@baybara-pavel Dependency array on `history` object should be `[pathname, location, router]`.

**Comment by amannn** [comment]
Thanks everyone for the collaboration here! I took the liberty of moving the code to a reusable package to avoid copy-pasting this from project to project: [`next-query-params`](https://github.com/amannn/react-hooks/tree/main/packages/next-query-params).

It compiles the `query-string` dependency, so you can use the latest version of it and still support IE11. It also fixes a bug with SSG where you'd have markup mismatches initially, since the server doesn't know about the query object. Furthermore the types of the provider are a bit more strict.

**Comment by fgblomqvist** [comment]
@pbeshai any comment on including this in the package? Would be neat to have built-in nextjs support. I don't think you would even have to maintain it, I'm sure people would be happy to help out with updating it/ensuring that it works.

**Comment by amannn** [comment]
A note for the people following along here: I've just published [`next-query-params@4.0.0`](https://github.com/amannn/next-query-params/blob/main/CHANGELOG.md#400-2022-08-30) which is based on `use-query-params@2` and the introduced concept of adapters.

This removes the necessity for a wrapper and integrates much better now, while still being able to use `use-query-params` directly.

**Comment by pbeshai** [comment]
If the adapter is working well, you're certainly welcome to PR it into this repo if you'd like. Thanks for taking the initiative on this work! 🙇

**Comment by optimistic-updt** [comment]
+1
amazing thread!
just looking to move over to NextJS and our app uses `useQueryParam` extensively, The adapter is on massive hurdle we don't have to deal with internally.
Would be dope to have it all integrated. :D

Now just need support for Next 13 😆 😆 😆

**Comment by Electron-2002** [comment]
Scroll to top is still happening when I am using `next-query-params@4.2.1`. Any solution for that?

I tried using this: https://github.com/pbeshai/use-query-params/issues/13#issuecomment-815577849, but it shows `NextRouter was not mounted`.

**Comment by Shahzad6077** [comment]
Hey @satejbidvai, could you able to fix the scrolling issue?
